/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as TimelineRouteImport } from './routes/timeline'
import { Route as IndexRouteImport } from './routes/index'
import { Route as LocationsSlugRouteImport } from './routes/locations.$slug'
import { Route as KeystaticIndexRouteImport } from './routes/keystatic/index'
import { Route as KeystaticSplatRouteImport } from './routes/keystatic/$'
import { Route as DemoTableRouteImport } from './routes/demo/table'
import { Route as ApiKeystaticIndexRouteImport } from './routes/api/keystatic/index'
import { Route as ApiKeystaticSplatRouteImport } from './routes/api/keystatic/$'

const TimelineRoute = TimelineRouteImport.update({
  id: '/timeline',
  path: '/timeline',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const LocationsSlugRoute = LocationsSlugRouteImport.update({
  id: '/locations/$slug',
  path: '/locations/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const KeystaticIndexRoute = KeystaticIndexRouteImport.update({
  id: '/keystatic/',
  path: '/keystatic/',
  getParentRoute: () => rootRouteImport,
} as any)
const KeystaticSplatRoute = KeystaticSplatRouteImport.update({
  id: '/keystatic/$',
  path: '/keystatic/$',
  getParentRoute: () => rootRouteImport,
} as any)
const DemoTableRoute = DemoTableRouteImport.update({
  id: '/demo/table',
  path: '/demo/table',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiKeystaticIndexRoute = ApiKeystaticIndexRouteImport.update({
  id: '/api/keystatic/',
  path: '/api/keystatic/',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiKeystaticSplatRoute = ApiKeystaticSplatRouteImport.update({
  id: '/api/keystatic/$',
  path: '/api/keystatic/$',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/timeline': typeof TimelineRoute
  '/locations/$slug': typeof LocationsSlugRoute
  '/demo/table': typeof DemoTableRoute
  '/keystatic/$': typeof KeystaticSplatRoute
  '/keystatic/': typeof KeystaticIndexRoute
  '/api/keystatic/$': typeof ApiKeystaticSplatRoute
  '/api/keystatic/': typeof ApiKeystaticIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/timeline': typeof TimelineRoute
  '/locations/$slug': typeof LocationsSlugRoute
  '/demo/table': typeof DemoTableRoute
  '/keystatic/$': typeof KeystaticSplatRoute
  '/keystatic': typeof KeystaticIndexRoute
  '/api/keystatic/$': typeof ApiKeystaticSplatRoute
  '/api/keystatic': typeof ApiKeystaticIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/timeline': typeof TimelineRoute
  '/locations/$slug': typeof LocationsSlugRoute
  '/demo/table': typeof DemoTableRoute
  '/keystatic/$': typeof KeystaticSplatRoute
  '/keystatic/': typeof KeystaticIndexRoute
  '/api/keystatic/$': typeof ApiKeystaticSplatRoute
  '/api/keystatic/': typeof ApiKeystaticIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/timeline'
    | '/locations/$slug'
    | '/demo/table'
    | '/keystatic/$'
    | '/keystatic/'
    | '/api/keystatic/$'
    | '/api/keystatic/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/timeline'
    | '/locations/$slug'
    | '/demo/table'
    | '/keystatic/$'
    | '/keystatic'
    | '/api/keystatic/$'
    | '/api/keystatic'
  id:
    | '__root__'
    | '/'
    | '/timeline'
    | '/locations/$slug'
    | '/demo/table'
    | '/keystatic/$'
    | '/keystatic/'
    | '/api/keystatic/$'
    | '/api/keystatic/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  TimelineRoute: typeof TimelineRoute
  LocationsSlugRoute: typeof LocationsSlugRoute
  DemoTableRoute: typeof DemoTableRoute
  KeystaticSplatRoute: typeof KeystaticSplatRoute
  KeystaticIndexRoute: typeof KeystaticIndexRoute
  ApiKeystaticSplatRoute: typeof ApiKeystaticSplatRoute
  ApiKeystaticIndexRoute: typeof ApiKeystaticIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/timeline': {
      id: '/timeline'
      path: '/timeline'
      fullPath: '/timeline'
      preLoaderRoute: typeof TimelineRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/locations/$slug': {
      id: '/locations/$slug'
      path: '/locations/$slug'
      fullPath: '/locations/$slug'
      preLoaderRoute: typeof LocationsSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/keystatic/': {
      id: '/keystatic/'
      path: '/keystatic'
      fullPath: '/keystatic/'
      preLoaderRoute: typeof KeystaticIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/keystatic/$': {
      id: '/keystatic/$'
      path: '/keystatic/$'
      fullPath: '/keystatic/$'
      preLoaderRoute: typeof KeystaticSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/demo/table': {
      id: '/demo/table'
      path: '/demo/table'
      fullPath: '/demo/table'
      preLoaderRoute: typeof DemoTableRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/keystatic/': {
      id: '/api/keystatic/'
      path: '/api/keystatic'
      fullPath: '/api/keystatic/'
      preLoaderRoute: typeof ApiKeystaticIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/keystatic/$': {
      id: '/api/keystatic/$'
      path: '/api/keystatic/$'
      fullPath: '/api/keystatic/$'
      preLoaderRoute: typeof ApiKeystaticSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  TimelineRoute: TimelineRoute,
  LocationsSlugRoute: LocationsSlugRoute,
  DemoTableRoute: DemoTableRoute,
  KeystaticSplatRoute: KeystaticSplatRoute,
  KeystaticIndexRoute: KeystaticIndexRoute,
  ApiKeystaticSplatRoute: ApiKeystaticSplatRoute,
  ApiKeystaticIndexRoute: ApiKeystaticIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
